In [3]:
# Reshaping 3x4 array to 2x2x3 array
import numpy as np
arr = np.array([1,2,3,4,5,6 ])


newarr = arr.reshape(2,3)

print("Original array:\n",arr)
print("--------------")
print("Reshaped array:\n", newarr)

Original array:
 [1 2 3 4 5 6]
--------------
Reshaped array:
 [[1 2 3]
 [4 5 6]]


### Flatten Array
- Flatten method flattens array to one dimension and returns copy of collapsed array

In [4]:
arr = np.array([[1,2,3], [4,5,6]])
flat_arr = arr.flatten()

print("Original array:\n", arr)
print("Flattened array:\n", flat_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
Flattened array:
 [1 2 3 4 5 6]


## NumPy Array Indexing and Slicing
## Basic Indexing
 Indexing allows us to access the individual elements or subsets of data

In [7]:
# 1D Array Indexing
arr = np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr[0]) # first element
print(arr[-1]) # last element
print(arr[3]) #fourth element

# 2D Array Inedxing 
num_2d_array = np.array([
                        [1,2,3],
                        [4,5,6],
                        [6,7,8]
])
print("print dimension of array")
print(num_2d_array.ndim) 
print("print shape of the array")
print(num_2d_array.shape)
print("print total number of items")
print(num_2d_array.size)

print("first row first element")
print(num_2d_array[0,0])
print("last row last element")
print(num_2d_array[-1,-1])
print("second row third element")
print(num_2d_array[1,2])
print("third row second element")
print(num_2d_array[2,1])




(6,)
1
6
4
print dimension of array
2
print shape of the array
(3, 3)
print total number of items
9
first row first element
1
last row last element
8
second row third element
6
third row second element
7


## Slicing in NumPy
In NumPy we can access the portion of an array using the slice operator

1-D Array Slicing 
syntax: array[start:stop:step]
- start: Index of the first element to be included in slice
- stop: index of the last element (exclusive)
- step: step size between each elemnt in the slice




In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,10,11])

# slice array from index 2-6 (6 exclusive)
print(arr[2:6])

# slice array from 0 to 8 with a step size of 2
print(arr[0:8:2])

# slice array from index 4 to last element
print(arr[4:])


# slice array from start to 5th index(5th index excluded)
print(arr[:5])

#negative index
print(arr[-1::-2]) # slice every second element from end to start


# we can also modify the array with slicing 
arr[:5] = 100 # replace items from 0-5 with 100
print(arr)




## 2-D Array Slicing
syntax: array[row_start:row_stop:row_step, col_start:col_stop:col_step]

In [9]:
array_2d = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
])
print(array_2d.ndim)

# slice first row
print(array_2d[0:1])

#slice array from first two rows and first tow columns

print(array_2d[0:2,0:2])

2
[[1 2 3]]
[[1 2]
 [4 5]]


## Boolean Array Indexing
Boolean array indexing allows us to select elemts from an array based on conditions. This technique is helpful when we need to filter elemts based on certain condtion. 

In [11]:
#creating an array
arr = np.array([5,10,15,20,25,30])

#slect elemtns greater than 15
print(arr[arr>15]) #output: [20 25 30]

#select elements that are even
print(arr[arr % 2 == 0])

#modifying elements that satisfy a condition
arr[arr > 15] = 99
print(arr)

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

#extract elements greater than 4
print(arr2d[arr2d > 4])

# Setting elements greater than 4 to zero
arr2d[arr2d > 4] = 0
print(arr2d)

[20 25 30]
[10 20 30]
[ 5 10 15 99 99 99]
[5 6 7 8 9]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


## NumPy Operation
• NumPy Arithmetic Array Operations

• NumPy Array Functions

• NumPy Comparison/Logical Operations

• NumPy Math Functions

• NumPy Constants

• NumPy Statistical Functions

## NumPy Arthimetic Operation 
- add()
- subract()
- multipy()
- divide()
- power()
- mod()


In [14]:
first_array = ([1, 3, 5, 6])
second_array = np.array([2,3,4,6])

print(np.add(first_array, second_array))
print(np.subtract(first_array, second_array))
print(np.multiply(first_array, second_array))
print(np.divide(first_array, second_array))
print(np.power(first_array, 2))
print(np.mod(first_array, second_array))

[ 3  6  9 12]
[-1  0  1  0]
[ 2  9 20 36]
[0.5  1.   1.25 1.  ]
[ 1  9 25 36]
[1 0 1 0]


## NumPy Broadcasting
- Broadcasting in NumPy allows it to perform arthimetic operations on array with different shapes

In [15]:
arr1 = np.array([1,2,3,4])
arr2 = np.array(4)
result = arr1 * arr2
print(result)

[ 4  8 12 16]


# NumPy Array Functions
= Outline •••

NumPy has various built-in functions for various purposes

• Array Creation Functions: np. array(), np. zeros(), p.ones ()

• Manipulation Functions: np.reshape(), np. transpose()np. empty() etc

• Mathematical Functions: np. add(), np. subtract(), np. sqrt(), np. power()

• Statistical Functions: np. median(), np.mean (), np.std(), np. var()

In [20]:
data = np.array([1,3,4,57,2,3])
print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

11.666666666666666
3.0
20.295045919851695
411.8888888888889


## Array Manipulation Functions 

In [23]:
numbers = np.array([1,2,3,4,5,6,7,8,9])

#reshape the 1D array into a 3D array
reshaped_array = np.reshape(numbers, (3,3))
print(reshaped_array)

#transpose
transposed_array = np.transpose(reshaped_array)
print(transposed_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# NumPy Matrix Operations
- Matrix Multiplication `np. matmul()`
- Dot Product `np.dot ()`
- Cross Product `np.cross()`
- Transpose `np.transpose`
- Inverse `np.linalg inverse()`
- Determinant `linalg.det()` linalg=>Linear Algebra
- Norm `np.linalg.norm()`
- Trace `np.linalg.trace()`

In [24]:
first_array = ([1,2,3])
second_array = ([4,5,6])
print(np.matmul(first_array, second_array))


32
